// <auto-generated />
using System;
using Katalog.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Katalog.Api.Infrastructure.Migrations
{
    [DbContext(typeof(KatalogContext))]
    partial class KatalogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Katalog.Api.Domain.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<int>("AlbumType")
                        .HasColumnType("integer")
                        .HasColumnName("album_type");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("external_url");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image_url");

                    b.Property<Guid?>("LabelId")
                        .HasColumnType("uuid")
                        .HasColumnName("label_id");

                    b.Property<string>("LabelSpotify")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("label_spotify");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<int>("ReleaseDatePrecision")
                        .HasColumnType("integer")
                        .HasColumnName("release_date_precision");

                    b.Property<string>("SpotifyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("spotify_id");

                    b.Property<int>("TotalTracks")
                        .HasColumnType("integer")
                        .HasColumnName("total_tracks");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_albums");

                    b.HasIndex("LabelId")
                        .HasDatabaseName("ix_albums_label_id");

                    b.HasIndex("SpotifyId")
                        .IsUnique()
                        .HasDatabaseName("ix_albums_spotify_id");

                    b.ToTable("albums", (string)null);
                });

            modelBuilder.Entity("Katalog.Api.Domain.AlbumArtist", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid")
                        .HasColumnName("album_id");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("AlbumId", "ArtistId")
                        .HasName("pk_album_artists");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("ix_album_artists_artist_id");

                    b.ToTable("album_artists", (string)null);
                });

            modelBuilder.Entity("Katalog.Api.Domain.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("external_url");

                    b.PrimitiveCollection<string[]>("Genres")
                        .HasColumnType("text[]")
                        .HasColumnName("genres");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int?>("Popularity")
                        .HasColumnType("integer")
                        .HasColumnName("popularity");

                    b.Property<string>("SpotifyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("spotify_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_artists");

                    b.HasIndex("SpotifyId")
                        .IsUnique()
                        .HasDatabaseName("ix_artists_spotify_id");

                    b.ToTable("artists", (string)null);
                });

            modelBuilder.Entity("Katalog.Api.Domain.Label", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_labels");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_labels_slug");

                    b.ToTable("labels", (string)null);
                });

            modelBuilder.Entity("Katalog.Api.Domain.LabelArtist", b =>
                {
                    b.Property<Guid>("LabelId")
                        .HasColumnType("uuid")
                        .HasColumnName("label_id");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<DateTimeOffset>("FirstSeenAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("first_seen_at_utc");

                    b.Property<DateTimeOffset>("LastConfirmedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_confirmed_at_utc");

                    b.Property<int>("Provenance")
                        .HasColumnType("integer")
                        .HasColumnName("provenance");

                    b.HasKey("LabelId", "ArtistId")
                        .HasName("pk_artist_label");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("ix_artist_label_artist_id");

                    b.ToTable("artist_label", (string)null);
                });

            modelBuilder.Entity("Katalog.Api.Domain.PollCursor", b =>
                {
                    b.Property<string>("JobName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("job_name");

                    b.Property<DateTimeOffset?>("CursorValue")
                        .HasColumnType("timestamptz")
                        .HasColumnName("cursor_value");

                    b.Property<DateTimeOffset?>("LastRunAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_run_at");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("JobName")
                        .HasName("pk_poll_cursors");

                    b.ToTable("poll_cursors", (string)null);
                });

            modelBuilder.Entity("Katalog.Api.Domain.Album", b =>
                {
                    b.HasOne("Katalog.Api.Domain.Label", null)
                        .WithMany()
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_albums_labels_label_id");
                });

            modelBuilder.Entity("Katalog.Api.Domain.AlbumArtist", b =>
                {
                    b.HasOne("Katalog.Api.Domain.Album", "Album")
                        .WithMany("AlbumArtists")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_album_artists_albums_album_id");

                    b.HasOne("Katalog.Api.Domain.Artist", "Artist")
                        .WithMany("AlbumArtists")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_album_artists_artists_artist_id");

                    b.Navigation("Album");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Katalog.Api.Domain.LabelArtist", b =>
                {
                    b.HasOne("Katalog.Api.Domain.Artist", "Artist")
                        .WithMany("LabelArtists")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artist_label_artists_artist_id");

                    b.HasOne("Katalog.Api.Domain.Label", "Label")
                        .WithMany("LabelArtists")
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artist_label_labels_label_id");

                    b.Navigation("Artist");

                    b.Navigation("Label");
                });

            modelBuilder.Entity("Katalog.Api.Domain.Album", b =>
                {
                    b.Navigation("AlbumArtists");
                });

            modelBuilder.Entity("Katalog.Api.Domain.Artist", b =>
                {
                    b.Navigation("AlbumArtists");

                    b.Navigation("LabelArtists");
                });

            modelBuilder.Entity("Katalog.Api.Domain.Label", b =>
                {
                    b.Navigation("LabelArtists");
                });
#pragma warning restore 612, 618
        }
    }
}
